### ISSUE TITLE
Remove default fade animation

### ISSUE THREAD

**Issue by mizuki-momose** [s-n-1-0/bs-modal.vue#2]
bs-modal.vueにてclass="modal fade"となっていますが、私の使用環境ではfadeなしで運用したいと思っています。
fade自体はmodalの必須要素ではないと思っているためbs-modal.vueからは削除し、必要であれば`<bs-modal class="fade">`とすればよいと思うのですがいかがでしょうか。

**Comment by s-n-1-0** [comment]
ご連絡くださりありがとうございます。

> fade自体はmodalの必須要素ではないと思っているためbs-modal.vueからは削除し、必要であればとすればよいと思うのですがいかがでしょうか。

確かにそうですね、fadeアニメーションを削除したバージョンを本日中にリリースしたいと思います。

**Comment by s-n-1-0** [comment]
Supported in v1.0.3.
b6beae93ff194bc719cbc34c5db2f9301fd9a23d
